#!/usr/bin/env bash

set -e

CLASS_DIR=~/.local/share/jdcli/classes

class_name="$1"

if ! test "$class_name"; then
    echo "Usage: $0 <class name>" >&2
    exit 1
fi

class_file="$CLASS_DIR/"$(echo $class_name | sed 's_\._/_g').txt

if ! [ -f "$class_file" ]; then
    echo "Class not found: $class_name" >&2
    n=0
    for line in $(grep --color=always -i -F -m 11 "$class_name" ~/.local/share/jdcli/classes/.index); do
        if [ $n -eq 10 ]; then
            echo "[...]"
            break
        fi
        n=$(($n+1))
        echo "$line"
    done
    exit 2
fi

less --raw-control-chars "$class_file"
